In [1]:
import numpy as np
joint_prob_XY = np.array([[0.10, 0.09, 0.11], [0.08, 0.07, 0.07], [0.18, 0.13, 0.17]])
joint_prob_XY

array([[ 0.1 ,  0.09,  0.11],
       [ 0.08,  0.07,  0.07],
       [ 0.18,  0.13,  0.17]])

In [2]:
prob_X = joint_prob_XY.sum(axis=1)
prob_X

array([ 0.3 ,  0.22,  0.48])

In [3]:
prob_Y = joint_prob_XY.sum(axis=0)
prob_Y

array([ 0.36,  0.29,  0.35])

In [4]:
joint_prob_XY_indep = np.outer(prob_X, prob_Y)
joint_prob_XY_indep

array([[ 0.108 ,  0.087 ,  0.105 ],
       [ 0.0792,  0.0638,  0.077 ],
       [ 0.1728,  0.1392,  0.168 ]])